# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findEndOfTag <- function(string, is_code = FALSE) {
    .Call('roxydoxy_findEndOfTag', PACKAGE = 'roxydoxy', string, is_code)
}

rdComplete <- function(string, is_code = FALSE) {
    .Call('roxydoxy_rdComplete', PACKAGE = 'roxydoxy', string, is_code)
}

leadingSpaces <- function(lines) {
    .Call('roxydoxy_leadingSpaces', PACKAGE = 'roxydoxy', lines)
}

tokenise_block <- function(lines, file = "", offset = 0L) {
    .Call('roxydoxy_tokenise_block', PACKAGE = 'roxydoxy', lines, file, offset)
}

find_includes <- function(path) {
    .Call('roxydoxy_find_includes', PACKAGE = 'roxydoxy', path)
}

splitByWhitespace <- function(string) {
    .Call('roxydoxy_splitByWhitespace', PACKAGE = 'roxydoxy', string)
}

wrapString <- function(string, width = 80L, indent = 2L) {
    .Call('roxydoxy_wrapString', PACKAGE = 'roxydoxy', string, width, indent)
}

